var COUNTRY = {
    'ML': [{ code: 'CHN', name: '中国' }],
    'HK': [{ code: 'TWN', name: '中国台湾' }, { code: 'HKG', name: '香港' }, { code: 'MAC', name: '澳门' }],
    'OS': [{
            "code": "GRC",
            "name": "希腊",
        },
        {
            "code": "HUN",
            "name": "匈牙利",
        },
        {
            "code": "ITA",
            "name": "意大利",
        },
        {
            "code": "GBR",
            "name": "英国",
        },
        {
            "code": "VAT",
            "name": "梵蒂冈",
        },
        {
            "code": "FRO",
            "name": "法罗群岛（丹麦属）",
        },
        {
            "code": "GIB",
            "name": "直布罗陀",
        },
        {
            "code": "REU",
            "name": "留尼汪（法属）",
        },
        {
            "code": "PYF",
            "name": "法属波利尼西亚（法属）",
        },
        {
            "code": "ATF",
            "name": "法属南部领地（法属）",
        },
        {
            "code": "MTQ",
            "name": "马提尼克（法属）",
        },
        {
            "code": "GLP",
            "name": "瓜德罗普（法属）",
        },
        {
            "code": "MYT",
            "name": "马约特（法属）",
        },
        {
            "code": "SPM",
            "name": "圣皮埃尔和密克隆（法属）",
        },
        {
            "code": "WLF",
            "name": "瓦利斯和富图纳（法属）",
        },
        {
            "code": "NCL",
            "name": "新喀里多尼亚（法属）",
        },
        {
            "code": "VGB",
            "name": "英属维尔京群岛",
        },
        {
            "code": "IOT",
            "name": "英属印度洋领地",
        },
        {
            "code": "SJM",
            "name": "斯瓦尔巴岛和扬马延岛",
        },
        {
            "code": "ARG",
            "name": "阿根廷",
        },
        {
            "code": "ATG",
            "name": "安提瓜和巴布达",
        },
        {
            "code": "BRB",
            "name": "巴巴多斯",
        },
        {
            "code": "BOL",
            "name": "玻利维亚",
        },
        {
            "code": "BRA",
            "name": "巴西",
        },
        {
            "code": "DMA",
            "name": "多米尼克",
        },
        {
            "code": "ECU",
            "name": "厄瓜多尔",
        },
        {
            "code": "COL",
            "name": "哥伦比亚",
        },
        {
            "code": "CUB",
            "name": "古巴",
        },
        {
            "code": "GRD",
            "name": "格林纳达",
        },
        {
            "code": "GUY",
            "name": "圭亚那",
        },
        {
            "code": "CAN",
            "name": "加拿大",
        },
        {
            "code": "PER",
            "name": "秘鲁",
        },
        {
            "code": "USA",
            "name": "美国",
        },
        {
            "code": "MEX",
            "name": "墨西哥",
        },
        {
            "code": "SUR",
            "name": "苏里南",
        },
        {
            "code": "LCA",
            "name": "圣卢西亚",
        },
        {
            "code": "TTO",
            "name": "特立尼达和多巴哥",
        },
        {
            "code": "VEN",
            "name": "委内瑞拉",
        },
        {
            "code": "URY",
            "name": "乌拉圭",
        },
        {
            "code": "JAM",
            "name": "牙买加",
        },
        {
            "code": "CHL",
            "name": "智利",
        },
        {
            "code": "ABW",
            "name": "阿鲁巴",
        },
        {
            "code": "AIA",
            "name": "安圭拉",
        },
        {
            "code": "PRY",
            "name": "巴拉圭",
        },
        {
            "code": "PAN",
            "name": "巴拿马",
        },
        {
            "code": "BMU",
            "name": "百慕大",
        },
        {
            "code": "PRI",
            "name": "波多黎各",
        },
        {
            "code": "BLZ",
            "name": "伯利兹",
        },
        {
            "code": "DOM",
            "name": "多米尼加",
        },
        {
            "code": "GUF",
            "name": "法属圭亚那",
        },
        {
            "code": "CRI",
            "name": "哥斯达黎加",
        },
        {
            "code": "GRL",
            "name": "格陵兰",
        },
        {
            "code": "HTI",
            "name": "海地",
        },
        {
            "code": "ANT",
            "name": "荷属安的列斯",
        },
        {
            "code": "HND",
            "name": "洪都拉斯",
        },
        {
            "code": "CYM",
            "name": "开曼群岛",
        },
        {
            "code": "VIR",
            "name": "美属维尔京群岛",
        },
        {
            "code": "GTM",
            "name": "危地马拉",
        },
        {
            "code": "UMI",
            "name": "美属本土外小岛屿",
        },
        {
            "code": "MNP",
            "name": "北马里亚纳（美托管）",
        },
        {
            "code": "MHL",
            "name": "马绍尔群岛（美托管",
        },
        {
            "code": "FLK",
            "name": "福克兰群岛（马尔维纳斯群岛）",
        },
        {
            "code": "SGS",
            "name": "南乔治亚岛和南桑威奇群岛",
        },
        {
            "code": "GUM",
            "name": "关岛（美属）",
        },
        {
            "code": "KNA",
            "name": "圣基茨和尼维斯",
        },
        {
            "code": "AUS",
            "name": "澳大利亚",
        },
        {
            "code": "PNG",
            "name": "巴布亚新几内亚",
        },
        {
            "code": "FJI",
            "name": "斐济",
        },
        {
            "code": "COK",
            "name": "库克群岛",
        },
        {
            "code": "ASM",
            "name": "美属萨摩亚",
        },
        {
            "code": "FSM",
            "name": "密克罗尼西亚联邦",
        },
        {
            "code": "NRU",
            "name": "瑙鲁",
        },
        {
            "code": "WSM",
            "name": "萨摩亚",
        },
        {
            "code": "TON",
            "name": "汤加",
        },
        {
            "code": "VUT",
            "name": "瓦努阿图",
        },
        {
            "code": "HMD",
            "name": "赫德岛和麦克唐纳岛",
        },
        {
            "code": "CCK",
            "name": "科克斯（基林）群岛",
        },
        {
            "code": "NZL",
            "name": "新西兰",
        },
        {
            "code": "NFK",
            "name": "诺福克岛",
        },
        {
            "code": "SLB",
            "name": "所罗门群岛",
        },
        {
            "code": "PCN",
            "name": "皮特凯恩",
        },
        {
            "code": "NIU",
            "name": "纽埃",
        },
        {
            "code": "TKL",
            "name": "托克劳",
        },
        {
            "code": "TUV",
            "name": "图瓦卢",
        },
        {
            "code": "KIR",
            "name": "基里巴斯",
        },
        {
            "code": "BVT",
            "name": "布维岛",
        },
        {
            "code": "CXR",
            "name": "圣诞岛",
        },
        {
            "code": "ATA",
            "name": "南极洲",
        },
        {
            "code": "TCA",
            "name": "特克斯和凯科斯群岛",
        },
        {
            "code": "ALB",
            "name": "阿尔巴尼亚",
        },
        {
            "code": "IRL",
            "name": "爱尔兰",
        },
        {
            "code": "EST",
            "name": "爱沙尼亚",
        },
        {
            "code": "AND",
            "name": "安道尔",
        },
        {
            "code": "AUT",
            "name": "奥地利",
        },
        {
            "code": "BEL",
            "name": "比利时",
        },
        {
            "code": "ISL",
            "name": "冰岛",
        },
        {
            "code": "CYP",
            "name": "塞浦路斯",
        },
        {
            "code": "BIH",
            "name": "波黑",
        },
        {
            "code": "POL",
            "name": "波兰",
        },
        {
            "code": "BGR",
            "name": "保加利亚",
        },
        {
            "code": "BLR",
            "name": "白俄罗斯",
        },
        {
            "code": "DNK",
            "name": "丹麦",
        },
        {
            "code": "DEU",
            "name": "德国",
        },
        {
            "code": "RUS",
            "name": "俄罗斯联邦",
        },
        {
            "code": "FRA",
            "name": "法国",
        },
        {
            "code": "FIN",
            "name": "芬兰",
        },
        {
            "code": "NLD",
            "name": "荷兰",
        },
        {
            "code": "MNE",
            "name": "黑山",
        },
        {
            "code": "CZE",
            "name": "捷克",
        },
        {
            "code": "HRV",
            "name": "克罗地亚",
        },
        {
            "code": "LVA",
            "name": "拉脱维亚",
        },
        {
            "code": "LTU",
            "name": "立陶宛",
        },
        {
            "code": "LIE",
            "name": "列支敦士登",
        },
        {
            "code": "LUX",
            "name": "卢森堡",
        },
        {
            "code": "ROM",
            "name": "罗马尼亚",
        },
        {
            "code": "MLT",
            "name": "马耳他",
        },
        {
            "code": "MKD",
            "name": "前南马其顿",
        },
        {
            "code": "MDA",
            "name": "摩尔多瓦",
        },
        {
            "code": "MCO",
            "name": "摩纳哥",
        },
        {
            "code": "NOR",
            "name": "挪威",
        },
        {
            "code": "PRT",
            "name": "葡萄牙",
        },
        {
            "code": "SWE",
            "name": "瑞典",
        },
        {
            "code": "CHE",
            "name": "瑞士",
        },
        {
            "code": "SRB",
            "name": "塞尔维亚",
        },
        {
            "code": "SVK",
            "name": "斯洛伐克",
        },
        {
            "code": "SVN",
            "name": "斯洛文尼亚",
        },
        {
            "code": "SMR",
            "name": "圣马力诺",
        },
        {
            "code": "UKR",
            "name": "乌克兰",
        },
        {
            "code": "ESP",
            "name": "西班牙",
        },
        {
            "code": "IDN",
            "name": "印度尼西亚",
        },
        {
            "code": "TZA",
            "name": "坦桑尼亚",
        },
        {
            "code": "MDV",
            "name": "马尔代夫",
        },
        {
            "code": "NER",
            "name": "尼日尔",
            "parent_id": 2,
            "code": "SYC",
            "name": "塞舌尔",
        },
        {
            "code": "ESH",
            "name": "西撒哈拉",
        },
        {
            "code": "BHS",
            "name": "巴哈马",
        },
        {
            "code": "MSR",
            "name": "蒙特塞拉特",
        },
        {
            "code": "NIC",
            "name": "尼加拉瓜",
        },
        {
            "code": "SLV",
            "name": "萨尔瓦多",
        },
        {
            "code": "VCT",
            "name": "圣文森特和格林纳丁斯",
        },
        {
            "code": "GHA",
            "name": "加纳",
            "parent_id": 2,
            "code": "SOM",
            "name": "索马里",
            "parent_id": 2,
            "code": "TUN",
            "name": "突尼斯",
            "parent_id": 2,
            "code": "UGA",
            "name": "乌干达",
            "parent_id": 2,
            "code": "ZMB",
            "name": "赞比亚",
            "parent_id": 2,
            "code": "TCD",
            "name": "乍得",
            "parent_id": 2,
            "code": "CAF",
            "name": "中非",
            "parent_id": 2,
            "code": "AFG",
            "name": "阿富汗",
            "parent_id": 2,
            "code": "ARE",
            "name": "阿联酋",
            "parent_id": 2,
            "code": "OMN",
            "name": "阿曼",
            "parent_id": 2,
            "code": "AZE",
            "name": "阿塞拜疆",
            "parent_id": 2,
            "code": "PAK",
            "name": "巴基斯坦",
            "parent_id": 2,
            "code": "PSE",
            "name": "巴勒斯坦",
            "parent_id": 2,
            "code": "BHR",
            "name": "巴林",
            "parent_id": 2,
            "code": "BTN",
            "name": "不丹",
            "parent_id": 2,
            "code": "PRK",
            "name": "朝鲜",
            "parent_id": 2,
            "code": "TMP",
            "name": "东帝汶",
            "parent_id": 2,
            "code": "PHL",
            "name": "菲律宾",
            "parent_id": 2,
            "code": "GEO",
            "name": "格鲁吉亚",
            "parent_id": 2,
            "code": "KAZ",
            "name": "哈萨克斯坦",
            "parent_id": 2,
            "code": "KOR",
            "name": "韩国",
            "parent_id": 2,
            "code": "KGZ",
            "name": "吉尔吉斯斯坦",
            "parent_id": 2,
            "code": "KHM",
            "name": "柬埔寨",
            "parent_id": 2,
            "code": "QAT",
            "name": "卡塔尔",
            "parent_id": 2,
            "code": "KWT",
            "name": "科威特",
            "parent_id": 2,
            "code": "LAO",
            "name": "老挝",
            "parent_id": 2,
            "code": "LBN",
            "name": "黎巴嫩",
            "parent_id": 2,
            "code": "MDV",
            "name": "马来西亚",
            "parent_id": 2,
            "code": "MNG",
            "name": "蒙古",
            "parent_id": 2,
            "code": "BGD",
            "name": "孟加拉国",
            "parent_id": 2,
            "code": "MMR",
            "name": "缅甸",
            "parent_id": 2,
            "code": "NPL",
            "name": "尼泊尔",
            "parent_id": 2,
            "code": "JPN",
            "name": "日本",
            "parent_id": 2,
            "code": "SAU",
            "name": "沙特阿拉伯",
            "parent_id": 2,
            "code": "LKA",
            "name": "斯里兰卡",
            "parent_id": 2,
            "code": "TJK",
            "name": "塔吉克斯坦",
            "parent_id": 2,
            "code": "THA",
            "name": "泰国",
            "parent_id": 2,
            "code": "TUR",
            "name": "土耳其",
            "parent_id": 2,
            "code": "TKM",
            "name": "土库曼斯坦",
            "parent_id": 2,
            "code": "BRN",
            "name": "文莱",
            "parent_id": 2,
            "code": "UZB",
            "name": "乌兹别克斯坦",
            "parent_id": 2,
            "code": "SGP",
            "name": "新加坡",
            "parent_id": 2,
            "code": "SYR",
            "name": "叙利亚",
            "parent_id": 2,
            "code": "ARM",
            "name": "亚美尼亚",
            "parent_id": 2,
            "code": "YEM",
            "name": "也门",
            "parent_id": 2,
            "code": "IRQ",
            "name": "伊拉克",
            "parent_id": 2,
            "code": "IRN",
            "name": "伊朗",
            "parent_id": 2,
            "code": "ISR",
            "name": "以色列",
            "parent_id": 2,
            "code": "IND",
            "name": "印度",
            "parent_id": 2,
            "code": "JOR",
            "name": "约旦",
            "parent_id": 2,
            "code": "VNM",
            "name": "越南",
            "parent_id": 2,
            "code": "PLW",
            "name": "帕劳",
            "parent_id": 2,
            "code": "DZA",
            "name": "阿尔及利亚",
            "parent_id": 2,
            "code": "EGY",
            "name": "埃及",
            "parent_id": 2,
            "code": "ETH",
            "name": "埃塞俄比亚",
            "parent_id": 2,
            "code": "AGO",
            "name": "安哥拉",
            "parent_id": 2,
            "code": "BEN",
            "name": "贝宁",
            "parent_id": 2,
            "code": "BWA",
            "name": "博茨瓦纳",
            "parent_id": 2,
            "code": "BFA",
            "name": "布基纳法索",
            "parent_id": 2,
            "code": "BDI",
            "name": "布隆迪",
            "parent_id": 2,
            "code": "GNQ",
            "name": "赤道几内亚",
            "parent_id": 2,
            "code": "TGO",
            "name": "多哥",
            "parent_id": 2,
            "code": "ERI",
            "name": "厄立特里亚",
            "parent_id": 2,
            "code": "CPV",
            "name": "佛得角",
            "parent_id": 2,
            "code": "GMB",
            "name": "冈比亚",
            "parent_id": 2,
            "code": "COG",
            "name": "刚果（布）",
            "parent_id": 2,
            "code": "COD",
            "name": "刚果（金）",
            "parent_id": 2,
            "code": "DJI",
            "name": "吉布提",
            "parent_id": 2,
            "code": "GIN",
            "name": "几内亚",
            "parent_id": 2,
            "code": "GNB",
            "name": "几内亚比绍",
            "parent_id": 2,
            "code": "GAB",
            "name": "加蓬",
            "parent_id": 2,
            "code": "ZWE",
            "name": "津巴布韦",
            "parent_id": 2,
            "code": "CMR",
            "name": "喀麦隆",
            "parent_id": 2,
            "code": "COM",
            "name": "科摩罗",
            "parent_id": 2,
            "code": "CIV",
            "name": "科特迪瓦",
            "parent_id": 2,
            "code": "KEN",
            "name": "肯尼亚",
            "parent_id": 2,
            "code": "LSO",
            "name": "莱索托",
            "parent_id": 2,
            "code": "LBR",
            "name": "利比里亚",
            "parent_id": 2,
            "code": "LBY",
            "name": "利比亚",
            "parent_id": 2,
            "code": "RWA",
            "name": "卢旺达",
            "parent_id": 2,
            "code": "MDG",
            "name": "马达加斯加",
            "parent_id": 2,
            "code": "MLI",
            "name": "马里",
            "parent_id": 2,
            "code": "MUS",
            "name": "毛里求斯",
            "parent_id": 2,
            "code": "MRT",
            "name": "毛里塔尼亚",
            "parent_id": 2,
            "code": "MAR",
            "name": "摩洛哥",
            "parent_id": 2,
            "code": "MOZ",
            "name": "莫桑比亚",
            "parent_id": 2,
            "code": "NAM",
            "name": "纳米比亚",
            "parent_id": 2,
            "code": "ZAF",
            "name": "南非",
            "parent_id": 2,
            "code": "SSD",
            "name": "南苏丹",
            "parent_id": 2,
            "code": "NGA",
            "name": "尼日利亚",
            "parent_id": 2,
            "code": "SLE",
            "name": "塞拉利昂",
            "parent_id": 2,
            "code": "SEN",
            "name": "塞内加尔",
        },
        {
            "code": "STP",
            "name": "圣多美和普林西比",
        },
        {
            "code": "SDN",
            "name": "苏丹",
        },
        {
            "code": "SWZ",
            "name": "斯威士兰",
        },
        {
            "code": "MWI",
            "name": "马拉维",
        },
        {
            "code": "SHN",
            "name": "圣赫勒拿",
        }
    ]

};